//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class xml_validate_errs {
    
    private xml_validate_errsRoot[] rootField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("root")]
    public xml_validate_errsRoot[] root {
        get {
            return this.rootField;
        }
        set {
            this.rootField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xml_validate_errsRoot {
    
    private int err_lineField;
    
    private string err_descriptionField;
    
    /// <remarks/>
    public int err_line {
        get {
            return this.err_lineField;
        }
        set {
            this.err_lineField = value;
        }
    }
    
    /// <remarks/>
    public string err_description {
        get {
            return this.err_descriptionField;
        }
        set {
            this.err_descriptionField = value;
        }
    }
}
