<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_1_50_161">
          <Public val="map_1_50_161"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="737509" _time="34501" date="25//3//2020" time="09:35:01.8600453"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="4_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="1"/>
            <_TotalVirtuals val="1"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="2"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="6"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="10"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="11"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="14"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="7"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="19"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="20"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="21"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="22"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="23"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="16"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="25"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="FileDelete(TranslateNR(getFullPath(RepStr ( GetParam ('000000000001000000000050F.TempFilePath') ,'.txt','.xml'))))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (GetParam ('000000000001000000000050F.XMLpathfile')))))&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (GetParam ('000000000001000000000050F.XMLpathfile')))))=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="NOT(iBolt_FileExist (Trim(Flip(Del(Flip(TranslateNR(getFullPath(RepStr ( GetParam ('000000000001000000000050F.TempFilePath') ,'.txt','.xml')))),1,InStr(Flip(TranslateNR(getFullPath(RepStr ( GetParam ('000000000001000000000050F.TempFilePath') ,'.txt','.xml')))),trim(TranslateNR ('%sl%'))))))))"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Destination directory does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="737509" _time="34501" date="25//3//2020" time="09:35:01.8630523"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO>
              <Description val="xmlSource_1_50_161_5"/>
              <IOExpression val="1"/>
              <OpenPrintDialog val="N"/>
              <PaperSize val="68"/>
              <Format val="N"/>
              <Media val="D"/>
              <Access val="R"/>
              <Copies val="1"/>
              <Orientation val="P"/>
              <PrintPreview val="N"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="A"/>
                    <WithValue val="10"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="2"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="6"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="9"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="TranslateNR(getFullPath(GetParam ('000000000001000000000050F.XMLpathfile')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="XMLCnt(0,1,'/ICM01001')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.openio',translatenr(getFullPath(RepStr ( GetParam ('000000000001000000000050F.TempFilePath') ,'.txt','.xml'))),'wb','16')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs_w','&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;no&quot; ?&gt;',A)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="UDF ('ibiowritter.insertNS_w','xsi','http://www.w3.org/2001/XMLSchema-instance',A)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','L','','','',A,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="UDF ('ibiowritter.closeio',A)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="NoSource_GeneralDestination">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="737509" _time="34501" date="25//3//2020" time="09:35:01.8640530"/>
            </Header>
            <ReturnValueExpression/>
            <Resource/>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <CallTask>
                      <OperationType val="T"/>
                      <TaskID comp="-1" obj="1"/>
                      <Lock val="N"/>
                      <Arguments/>
                      <Wait val="Y"/>
                      <SyncData val="N"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </CallTask>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Task>
              <Header Description="ICM01001/IDOC/ICM010">
                <Public/>
                <ExecutionRight/>
                <Resident val="N"/>
                <SQL val="N"/>
                <ReturnValue>
                  <ReturnValueAttr/>
                  <ParametersAttributes/>
                </ReturnValue>
                <SqlWhereExist val="N"/>
                <TaskType val="B"/>
                <External val="Y"/>
                <LastModified _date="737509" _time="34501" date="25//3//2020" time="09:35:01.8640530"/>
              </Header>
              <ReturnValueExpression/>
              <Resource>
                <Columns>
                  <Column id="1" name="D_4_ParentLine">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_NUMERIC"/>
                      <StoredAs val="6"/>
                      <Size val="8"/>
                      <_Dec val="0"/>
                      <_Whole val="7"/>
                      <_Negative val="0"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="7"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="2" name="D_4_PersonalID">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="3" name="D_4_PassportNo">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="4" name="D_4_FirstName">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="5" name="D_4_LastName">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="6" name="D_4_Consent_ID">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="7" name="D_4_ConsentValue">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="8" name="D_4_ConsentDate">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="9" name="D_4_First_Transition_date">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="10" name="D_4_Expiry_Date">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="11" name="D_4_Withdrawal_Date">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                </Columns>
              </Resource>
              <Information>
                <Key>
                  <Column/>
                  <Mode val="N"/>
                </Key>
                <DB/>
                <Sort>
                  <CLS val="A"/>
                </Sort>
                <ForceRecordDelete DEL="N"/>
                <EndTaskCondition val="Y" Exp="34"/>
                <EvaluateEndCondition val="A"/>
                <InitialMode val="M"/>
                <Locate Direction="A"/>
                <Range Direction="A"/>
                <VarRange/>
                <TaskProperties>
                  <SelectionTable val="N"/>
                  <ConfirmUpdate CNFU="N"/>
                  <ConfirmCancel val="N"/>
                  <ErrorStrategy val="R"/>
                  <LockingStrategy val="M"/>
                  <CacheStrategy val="T"/>
                  <ForceRecordSuffix val="N"/>
                  <TransactionMode val="P"/>
                  <TransactionBegin val="N"/>
                  <PreloadView val="N"/>
                  <KeepCreatedContext val="N"/>
                </TaskProperties>
                <SIDE_WIN>
                  <AllowOptions val="N"/>
                  <AllowQuery val="Y"/>
                  <AllowModify val="Y"/>
                  <AllowCreate val="Y"/>
                  <AllowDelete val="Y"/>
                  <AllowLocate val="Y"/>
                  <AllowRange val="Y"/>
                  <AllowIndexChange val="Y"/>
                  <AllowSorting val="Y"/>
                  <AllowIOFiles val="Y"/>
                  <RecordCycle val="Y"/>
                  <AllowEvents val="Y"/>
                  <AllowIndexOptimization val="Y"/>
                  <AllowLocationInQuery val="Y"/>
                  <AllowPrintingData val="N"/>
                </SIDE_WIN>
                <WIN>
                  <OpenTaskWindow val="N"/>
                  <CloseTaskWindow val="Y"/>
                  <ForegroundWindow val="Y"/>
                  <FlipFld val="N"/>
                  <RefreshTaskWindow ReturnValue="N"/>
                </WIN>
                <BOX>
                  <Direction val="V"/>
                </BOX>
              </Information>
              <TaskLogic>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="M"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <_TotalVariabls val="11"/>
                  <_TotalVirtuals val="11"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <DATAVIEW_SRC Type="M">
                        <Condition val="N"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </DATAVIEW_SRC>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="B">
                        <ASS/>
                        <Column val="1"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="C">
                        <ASS/>
                        <Column val="2"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="D">
                        <ASS/>
                        <Column val="3"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="E">
                        <ASS/>
                        <Column val="4"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="F">
                        <ASS/>
                        <Column val="5"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="G">
                        <ASS/>
                        <Column val="6"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="H">
                        <ASS/>
                        <Column val="7"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="I">
                        <ASS/>
                        <Column val="8"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="J">
                        <ASS/>
                        <Column val="9"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="K">
                        <ASS/>
                        <Column val="10"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="L">
                        <ASS/>
                        <Column val="11"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="16"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="17"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="18"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="19"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="20"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="21"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="23"/>
                        <ReturnValue/>
                        <Condition Exp="22"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="25"/>
                        <ReturnValue/>
                        <Condition Exp="24"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="26"/>
                        <ReturnValue/>
                        <Condition Exp="24"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="28"/>
                        <ReturnValue/>
                        <Condition Exp="27"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="29"/>
                        <ReturnValue/>
                        <Condition Exp="27"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="30"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="35"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=" **** Schema  Destination ****"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="36"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="B"/>
                        <WithValue val="37"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="38"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="C"/>
                        <WithValue val="39"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="40"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="D"/>
                        <WithValue val="41"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="42"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="E"/>
                        <WithValue val="43"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="44"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="F"/>
                        <WithValue val="45"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="46"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="G"/>
                        <WithValue val="47"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="48"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="H"/>
                        <WithValue val="49"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="50"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="I"/>
                        <WithValue val="51"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="52"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="J"/>
                        <WithValue val="53"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="54"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="K"/>
                        <WithValue val="55"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="56"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="L"/>
                        <WithValue val="57"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="58"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="1"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="2"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="3"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="6"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="7"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="8"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="11"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="12"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="13"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="4"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="5"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="9"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="10"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="14"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="15"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
              </TaskLogic>
              <TaskForms>
                <FormEntry _last_test_id="1">
                  <PropertyList model="FORM_GUI0">
                    <Width/>
                    <Height/>
                    <_Comment/>
                    <FormName valUnicode="Empty Program"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <Expressions>
                <Expression val="1">
                  <ExpSyntax val="SetParam('Temp_3_S_1_50_161_5_ICM01001/IDOC/ICM010_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_50_161_5_ICM01001/IDOC/ICM010'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="2">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_50_161_5_ICM01001/IDOC/ICM010_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC/ICM010'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="3">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC/ICM010',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="4">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC/ICM010',GetParam('Temp_3_S_1_50_161_5_ICM01001/IDOC/ICM010_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="5">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC/ICM010',GetParam('Temp_XMLCnt_3_S_1_50_161_5_ICM01001/IDOC/ICM010_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="6">
                  <ExpSyntax val="SetParam('Temp_3_S_1_50_161_5_ICM01001/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_50_161_5_ICM01001/IDOC'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="7">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_50_161_5_ICM01001/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="8">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="9">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC',GetParam('Temp_3_S_1_50_161_5_ICM01001/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="10">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC',GetParam('Temp_XMLCnt_3_S_1_50_161_5_ICM01001/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="11">
                  <ExpSyntax val="SetParam('Temp_3_S_1_50_161_5_ICM01001_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_50_161_5_ICM01001'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="12">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_50_161_5_ICM01001_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_50_161_5_ICM01001'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="13">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="14">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001',GetParam('Temp_3_S_1_50_161_5_ICM01001_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="15">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_50_161_5_ICM01001',GetParam('Temp_XMLCnt_3_S_1_50_161_5_ICM01001_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="16">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001/IDOC/ICM010')&gt;=GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC/ICM010')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="17">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC/ICM010',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="18">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001/IDOC')&gt;=GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="19">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="20">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001')&gt;=GetParam('XMLCnt_S_1_50_161_5_ICM01001')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="21">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="22">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="23">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_50_161_5_ICM01001',XMLCnt(2,1,'/ICM01001'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="24">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001/IDOC') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="25">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001',GetParam('S_1_50_161_5_ICM01001')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="26">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC',XMLCnt(2,1,'/ICM01001['&amp;Trim(Str(GetParam('S_1_50_161_5_ICM01001'),''))&amp;']/IDOC'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="27">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001/IDOC/ICM010') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="28">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC',GetParam('S_1_50_161_5_ICM01001/IDOC')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="29">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC/ICM010',XMLCnt(2,1,'/ICM01001['&amp;Trim(Str(GetParam('S_1_50_161_5_ICM01001'),''))&amp;']/IDOC['&amp;Trim(Str(GetParam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']/ICM010'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="30">
                  <ExpSyntax val="SetParam('S_1_50_161_5_ICM01001/IDOC/ICM010',GetParam('S_1_50_161_5_ICM01001/IDOC/ICM010')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="31">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001/IDOC/ICM010')&gt;=GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC/ICM010')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="32">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001/IDOC')&gt;=GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="33">
                  <ExpSyntax val="GetParam('S_1_50_161_5_ICM01001')&gt;=GetParam('XMLCnt_S_1_50_161_5_ICM01001')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="34">
                  <ExpSyntax val="(ExpCalc('31'EXP)  AND ExpCalc('32'EXP)  AND ExpCalc('33'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="35">
                  <ExpSyntax val="GetParam('XMLCnt_S_1_50_161_5_ICM01001/IDOC/ICM010')&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="36">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','C','ICM010','ICM01001/IDOC/ICM010','',A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="37">
                  <ExpSyntax val="Val(xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/ParentLine','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')),'N7')"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="38">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','ParentLine','ICM01001/IDOC/ICM010/ParentLine',trim(str(B,'N7')),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="39">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/PersonalID','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="40">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','PersonalID','ICM01001/IDOC/ICM010/PersonalID',rtrim(C),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="41">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/PassportNo','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="42">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','PassportNo','ICM01001/IDOC/ICM010/PassportNo',rtrim(D),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="43">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/FirstName','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="44">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','FirstName','ICM01001/IDOC/ICM010/FirstName',rtrim(E),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="45">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/LastName','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="46">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','LastName','ICM01001/IDOC/ICM010/LastName',rtrim(F),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="47">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/Consent_ID','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="48">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','Consent_ID','ICM01001/IDOC/ICM010/Consent_ID',rtrim(G),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="49">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/ConsentValue','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="50">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','ConsentValue','ICM01001/IDOC/ICM010/ConsentValue',rtrim(H),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="51">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/ConsentDate','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="52">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','ConsentDate','ICM01001/IDOC/ICM010/ConsentDate',rtrim(I),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="53">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/First_Transition_date','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="54">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','First_Transition_date','ICM01001/IDOC/ICM010/First_Transition_date',rtrim(J),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="55">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/Expiry_Date','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="56">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','Expiry_Date','ICM01001/IDOC/ICM010/Expiry_Date',rtrim(K),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="57">
                  <ExpSyntax val="xmlget(2,1,'/ICM01001['&amp;trim(str(getparam('S_1_50_161_5_ICM01001'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC'),''))&amp;']'&amp;'/ICM010['&amp;trim(str(getparam('S_1_50_161_5_ICM01001/IDOC/ICM010'),''))&amp;']'&amp;'/Withdrawal_Date','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="58">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','Withdrawal_Date','ICM01001/IDOC/ICM010/Withdrawal_Date',rtrim(L),A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
              </Expressions>
            </Task>
          </Task>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
