<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_1_7_39">
          <Public val="map_1_7_39"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="737509" _time="34505" date="25//3//2020" time="09:35:05.9558589"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="4_Destination_DataBlob">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_BLOB"/>
                <StoredAs val="34"/>
                <Size val="28"/>
                <_FieldStyle val="1"/>
                <Content val="2"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="1"/>
            <_TotalVirtuals val="1"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="3"/>
                  <ReturnValue/>
                  <Condition Exp="2"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="5"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="7"/>
                  <ReturnValue/>
                  <Condition Exp="6"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition Exp="6"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition Exp="6"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="10"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="11"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="6"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="14"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="16"/>
                  <ReturnValue/>
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="15"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="19"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="20"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="21"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="22"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="15"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="23"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="25"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (GetParam ('C.DestFilePath')))))&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (GetParam ('C.DestFilePath')))))=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="FileSize(trim(TranslateNR(getFullPath('%Schema%ICRM003\ICRM003_Merge.txt'))))=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Destination Template File does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="SetParam ('000000000001000000000007F.BlobforHoldingDetail',A)"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="737509" _time="34505" date="25//3//2020" time="09:35:05.9568537"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO>
              <Description val="xmlSource_1_7_39_3"/>
              <IOExpression val="1"/>
              <OpenPrintDialog val="N"/>
              <PaperSize val="68"/>
              <Format val="N"/>
              <Media val="D"/>
              <Access val="R"/>
              <Copies val="1"/>
              <Orientation val="P"/>
              <PrintPreview val="N"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
            <IO Column="A">
              <Description val="Template Dest"/>
              <Format val="N"/>
              <Media val="V"/>
              <Access val="W"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
              <CHARSET val="3"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="2"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="6"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="9"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="TranslateNR(getFullPath(GetParam ('C.DestFilePath')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="XMLCnt(0,1,'/ZSERCAM01')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="NoSource_GeneralDestination">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="737509" _time="34505" date="25//3//2020" time="09:35:05.9618469"/>
            </Header>
            <ReturnValueExpression/>
            <Resource/>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Destination Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <CallTask>
                      <OperationType val="T"/>
                      <TaskID comp="-1" obj="1"/>
                      <Lock val="N"/>
                      <Arguments/>
                      <Wait val="Y"/>
                      <SyncData val="N"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </CallTask>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Destination Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Task>
              <Header Description="Root/Repeat1">
                <Public/>
                <ExecutionRight/>
                <Resident val="N"/>
                <SQL val="N"/>
                <ReturnValue>
                  <ReturnValueAttr/>
                  <ParametersAttributes/>
                </ReturnValue>
                <SqlWhereExist val="N"/>
                <TaskType val="B"/>
                <External val="Y"/>
                <LastModified _date="737509" _time="34505" date="25//3//2020" time="09:35:05.9618469"/>
              </Header>
              <ReturnValueExpression/>
              <Resource>
                <Columns>
                  <Column id="1" name="D_4_CheckHeader">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_LOGICAL"/>
                      <StoredAs/>
                      <Size val="5"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="5"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="2" name="D_4_PHeader">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="3" name="D_4_PRoot">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="4" name="D_4_PLine">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="5" name="D_4_PCAMPAIGN_CODE">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="20"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="10"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="6" name="D_4_PCAMPAIGN_DESCRIPTION">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="7" name="D_4_PACTUAL_START_DATE">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="8" name="D_4_PACTUAL_END_DATE">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="2000"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="1000"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                  <Column id="9" name="D_4_PCAMPAIGN_STATUS">
                    <PropertyList model="FIELD">
                      <Model attr_obj="FIELD_UNICODE"/>
                      <StoredAs val="32"/>
                      <Size val="30"/>
                      <_FieldStyle val="1"/>
                      <Picture valUnicode="15"/>
                      <Definition val="2"/>
                    </PropertyList>
                  </Column>
                </Columns>
              </Resource>
              <Information>
                <Key>
                  <Column/>
                  <Mode val="N"/>
                </Key>
                <DB/>
                <Sort>
                  <CLS val="A"/>
                </Sort>
                <ForceRecordDelete DEL="N"/>
                <EndTaskCondition val="Y" Exp="34"/>
                <EvaluateEndCondition val="A"/>
                <InitialMode val="M"/>
                <Locate Direction="A"/>
                <Range Direction="A"/>
                <VarRange/>
                <TaskProperties>
                  <SelectionTable val="N"/>
                  <ConfirmUpdate CNFU="N"/>
                  <ConfirmCancel val="N"/>
                  <ErrorStrategy val="R"/>
                  <LockingStrategy val="M"/>
                  <CacheStrategy val="T"/>
                  <ForceRecordSuffix val="N"/>
                  <TransactionMode val="P"/>
                  <TransactionBegin val="N"/>
                  <PreloadView val="N"/>
                  <KeepCreatedContext val="N"/>
                </TaskProperties>
                <SIDE_WIN>
                  <AllowOptions val="N"/>
                  <AllowQuery val="Y"/>
                  <AllowModify val="Y"/>
                  <AllowCreate val="Y"/>
                  <AllowDelete val="Y"/>
                  <AllowLocate val="Y"/>
                  <AllowRange val="Y"/>
                  <AllowIndexChange val="Y"/>
                  <AllowSorting val="Y"/>
                  <AllowIOFiles val="Y"/>
                  <RecordCycle val="Y"/>
                  <AllowEvents val="Y"/>
                  <AllowIndexOptimization val="Y"/>
                  <AllowLocationInQuery val="Y"/>
                  <AllowPrintingData val="N"/>
                </SIDE_WIN>
                <WIN>
                  <OpenTaskWindow val="N"/>
                  <CloseTaskWindow val="Y"/>
                  <ForegroundWindow val="Y"/>
                  <FlipFld val="N"/>
                  <RefreshTaskWindow ReturnValue="N"/>
                </WIN>
                <BOX>
                  <Direction val="V"/>
                </BOX>
              </Information>
              <TaskLogic>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="M"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <_TotalVariabls val="9"/>
                  <_TotalVirtuals val="9"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <DATAVIEW_SRC Type="M">
                        <Condition val="N"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </DATAVIEW_SRC>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="B">
                        <ASS/>
                        <Column val="1"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="C">
                        <ASS/>
                        <Column val="2"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="D">
                        <ASS/>
                        <Column val="3"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="E">
                        <ASS/>
                        <Column val="4"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="F">
                        <ASS/>
                        <Column val="5"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="G">
                        <ASS/>
                        <Column val="6"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="H">
                        <ASS/>
                        <Column val="7"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="I">
                        <ASS/>
                        <Column val="8"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                    <LogicLine>
                      <Select Name="J">
                        <ASS/>
                        <Column val="9"/>
                        <Type val="V"/>
                        <IsParameter val="N"/>
                        <_RecomputeIndex val="1"/>
                        <_FormIndex val="1"/>
                        <_ControlIndex val="1"/>
                        <_OleSubformIdx val="1"/>
                        <_TabbingOrderDspIndex val="1"/>
                        <DIFF_UPDATE val="T"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </Select>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="16"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="17"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="18"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="19"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="20"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="21"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="23"/>
                        <ReturnValue/>
                        <Condition Exp="22"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="25"/>
                        <ReturnValue/>
                        <Condition Exp="24"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="26"/>
                        <ReturnValue/>
                        <Condition Exp="24"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="28"/>
                        <ReturnValue/>
                        <Condition Exp="27"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="29"/>
                        <ReturnValue/>
                        <Condition Exp="27"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="30"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="35"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=" **** Schema  Destination ****"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="36"/>
                        <ReturnValue/>
                        <Condition Exp="37"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="38"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="39"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="B"/>
                        <WithValue val="40"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="C"/>
                        <WithValue val="41"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="D"/>
                        <WithValue val="42"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="E"/>
                        <WithValue val="43"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="F"/>
                        <WithValue val="44"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="G"/>
                        <WithValue val="45"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="H"/>
                        <WithValue val="46"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="I"/>
                        <WithValue val="47"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Update>
                        <Variable val="J"/>
                        <WithValue val="48"/>
                        <Incremental val="N"/>
                        <ForcedUpdate val="Y"/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Update>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Destination Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <FormIO>
                        <OperationType val="O"/>
                        <Page val="A"/>
                        <IODeviceInfo>
                          <IoDeviceParent val="2"/>
                          <IoDeviceIndex val="2"/>
                        </IODeviceInfo>
                        <FormEntryInfo>
                          <FormEntryIndex val="2"/>
                        </FormEntryInfo>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </FormIO>
                    </LogicLine>
                    <LogicLine>
                      <CallTask>
                        <OperationType val="T"/>
                        <TaskID comp="-1" obj="1"/>
                        <Lock val="N"/>
                        <Arguments/>
                        <Wait val="Y"/>
                        <SyncData val="N"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </CallTask>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Destination Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="1"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="2"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="3"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="6"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="7"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="8"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="11"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="12"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="13"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="4"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="5"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="9"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="10"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="14"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="15"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
              </TaskLogic>
              <TaskForms>
                <FormEntry _last_test_id="1">
                  <PropertyList model="FORM_GUI0">
                    <Width/>
                    <Height/>
                    <_Comment/>
                    <FormName valUnicode="Empty Program"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <TaskForms>
                <FormEntry CLSS="6">
                  <PropertyList model="FORM_MERGE">
                    <FileName Exp="49"/>
                    <TagsTable>
                      <MERGE_PARM PIC_U="1" TXT_U="CheckHeader" id="1" Column="B"/>
                      <MERGE_PARM PIC_U="1000" TXT_U="PHeader" id="2" Column="C" TEXP="50"/>
                      <MERGE_PARM PIC_U="1000" TXT_U="PRoot" id="3" Column="D" TEXP="51"/>
                      <MERGE_PARM PIC_U="1000" TXT_U="PLine" id="4" Column="E" TEXP="52"/>
                      <MERGE_PARM PIC_U="10" TXT_U="PCAMPAIGN_CODE" id="5" Column="F" TEXP="53"/>
                      <MERGE_PARM PIC_U="1000" TXT_U="PCAMPAIGN_DESCRIPTION" id="6" Column="G" TEXP="54"/>
                      <MERGE_PARM PIC_U="1000" TXT_U="PACTUAL_START_DATE" id="7" Column="H" TEXP="55"/>
                      <MERGE_PARM PIC_U="1000" TXT_U="PACTUAL_END_DATE" id="8" Column="I" TEXP="56"/>
                      <MERGE_PARM PIC_U="15" TXT_U="PCAMPAIGN_STATUS" id="9" Column="J" TEXP="57"/>
                    </TagsTable>
                    <_Comment/>
                    <FormName valUnicode="Template Merge Destination_2"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <Expressions>
                <Expression val="1">
                  <ExpSyntax val="SetParam('Temp_3_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="2">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="3">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="4">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN',GetParam('Temp_3_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="5">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN',GetParam('Temp_XMLCnt_3_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="6">
                  <ExpSyntax val="SetParam('Temp_3_S_1_7_39_3_ZSERCAM01/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_7_39_3_ZSERCAM01/IDOC'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="7">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_7_39_3_ZSERCAM01/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="8">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="9">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC',GetParam('Temp_3_S_1_7_39_3_ZSERCAM01/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="10">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC',GetParam('Temp_XMLCnt_3_S_1_7_39_3_ZSERCAM01/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="11">
                  <ExpSyntax val="SetParam('Temp_3_S_1_7_39_3_ZSERCAM01_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_7_39_3_ZSERCAM01'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="12">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_7_39_3_ZSERCAM01_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="13">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="14">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01',GetParam('Temp_3_S_1_7_39_3_ZSERCAM01_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="15">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01',GetParam('Temp_XMLCnt_3_S_1_7_39_3_ZSERCAM01_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="16">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="17">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="18">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="19">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="20">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="21">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="22">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="23">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01',XMLCnt(2,1,'/ZSERCAM01'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="24">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="25">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01',GetParam('S_1_7_39_3_ZSERCAM01')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="26">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC',XMLCnt(2,1,'/ZSERCAM01['&amp;Trim(Str(GetParam('S_1_7_39_3_ZSERCAM01'),''))&amp;']/IDOC'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="27">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="28">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC',GetParam('S_1_7_39_3_ZSERCAM01/IDOC')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="29">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN',XMLCnt(2,1,'/ZSERCAM01['&amp;Trim(Str(GetParam('S_1_7_39_3_ZSERCAM01'),''))&amp;']/IDOC['&amp;Trim(Str(GetParam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']/ZSCAMPAIGN'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="30">
                  <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN',GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="31">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="32">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="33">
                  <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="34">
                  <ExpSyntax val="(ExpCalc('31'EXP)  AND ExpCalc('32'EXP)  AND ExpCalc('33'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="35">
                  <ExpSyntax val="GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN')&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="36">
                  <ExpSyntax val="SetParam ('000000000001000000000007F.LineNo',GetParam ('000000000001000000000007F.LineNo') +1)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="37">
                  <ExpSyntax val="InStr( GetParam ('000000000001000000000007F.Store_Invalid_Key_Values') ,'|'&amp;Trim( xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/CAMPAIGN_CODE','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')) )&amp;'|')=0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="38">
                  <ExpSyntax val="SetParam ('000000000001000000000007F.ParentLineNo',GetParam ('000000000001000000000007F.LineNo'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="39">
                  <ExpSyntax val="InStr( GetParam ('000000000001000000000007F.Store_Invalid_Key_Values') ,'|'&amp;Trim( xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/CAMPAIGN_CODE','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')) )&amp;'|')=0&#xD;&#xA;"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="40">
                  <ExpSyntax val="'TRUE'LOG"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="41">
                  <ExpSyntax val="rTrim( 'i' )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="42">
                  <ExpSyntax val="rTrim( 'p' )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="43">
                  <ExpSyntax val="rTrim( Str ( GetParam ('000000000001000000000007F.LineNo') ,IF ( GetParam ('000000000001000000000007F.LineNo') &lt;10,'1',IF ( GetParam ('000000000001000000000007F.LineNo') &lt;100,'2',IF ( GetParam ('000000000001000000000007F.LineNo') &lt;1000,'3',IF ( GetParam ('000000000001000000000007F.LineNo') &lt;10000,'4','5'))))) )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="44">
                  <ExpSyntax val="rTrim( Trim( xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/CAMPAIGN_CODE','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')) ) )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="45">
                  <ExpSyntax val="rTrim( Trim( xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/CAMPAIGN_DESCRIPTION','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')) ) )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="46">
                  <ExpSyntax val="xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/ACTUAL_START_DATE','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="47">
                  <ExpSyntax val="xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/ACTUAL_END_DATE','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="48">
                  <ExpSyntax val="rTrim( Trim( xmlget(2,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/CAMPAIGN_STATUS','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue')) ) )"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="49">
                  <ExpSyntax val="Translate(getFullPath('%Schema%ICRM003\ICRM003_Merge.txt'))"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="50">
                  <ExpSyntax val="Trim (Str (Len (RTrim (C)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="51">
                  <ExpSyntax val="Trim (Str (Len (RTrim (D)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="52">
                  <ExpSyntax val="Trim (Str (Len (RTrim (E)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="53">
                  <ExpSyntax val="Trim (Str (Len (RTrim (F)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="54">
                  <ExpSyntax val="Trim (Str (Len (RTrim (G)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="55">
                  <ExpSyntax val="Trim (Str (Len (RTrim (H)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="56">
                  <ExpSyntax val="Trim (Str (Len (RTrim (I)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="57">
                  <ExpSyntax val="Trim (Str (Len (RTrim (J)),'12'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
              </Expressions>
              <Task>
                <Header Description="Root/Repeat1/Repeat2">
                  <Public/>
                  <ExecutionRight/>
                  <Resident val="N"/>
                  <SQL val="N"/>
                  <ReturnValue>
                    <ReturnValueAttr/>
                    <ParametersAttributes/>
                  </ReturnValue>
                  <SqlWhereExist val="N"/>
                  <TaskType val="B"/>
                  <External val="Y"/>
                  <LastModified _date="737509" _time="34506" date="25//3//2020" time="09:35:06.0118517"/>
                </Header>
                <ReturnValueExpression/>
                <Resource>
                  <Columns>
                    <Column id="1" name="D_4_CheckDetail1">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_LOGICAL"/>
                        <StoredAs/>
                        <Size val="5"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="5"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="2" name="D_4_CHeader">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="3" name="D_4_CRoot">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="4" name="D_4_CLine">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="5" name="D_4_CParentLine">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="6" name="D_4_CTableName">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="7" name="D_4_CVIN_NUMBER">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                  </Columns>
                </Resource>
                <Information>
                  <Key>
                    <Column/>
                    <Mode val="N"/>
                  </Key>
                  <DB/>
                  <Sort>
                    <CLS val="A"/>
                  </Sort>
                  <ForceRecordDelete DEL="N"/>
                  <EndTaskCondition val="Y" Exp="12"/>
                  <EvaluateEndCondition val="A"/>
                  <InitialMode val="M"/>
                  <Locate Direction="A"/>
                  <Range Direction="A"/>
                  <VarRange/>
                  <TaskProperties>
                    <SelectionTable val="N"/>
                    <ConfirmUpdate CNFU="N"/>
                    <ConfirmCancel val="N"/>
                    <ErrorStrategy val="R"/>
                    <LockingStrategy val="M"/>
                    <CacheStrategy val="T"/>
                    <ForceRecordSuffix val="N"/>
                    <TransactionMode val="P"/>
                    <TransactionBegin val="N"/>
                    <PreloadView val="N"/>
                    <KeepCreatedContext val="N"/>
                  </TaskProperties>
                  <SIDE_WIN>
                    <AllowOptions val="N"/>
                    <AllowQuery val="Y"/>
                    <AllowModify val="Y"/>
                    <AllowCreate val="Y"/>
                    <AllowDelete val="Y"/>
                    <AllowLocate val="Y"/>
                    <AllowRange val="Y"/>
                    <AllowIndexChange val="Y"/>
                    <AllowSorting val="Y"/>
                    <AllowIOFiles val="Y"/>
                    <RecordCycle val="Y"/>
                    <AllowEvents val="Y"/>
                    <AllowIndexOptimization val="Y"/>
                    <AllowLocationInQuery val="Y"/>
                    <AllowPrintingData val="N"/>
                  </SIDE_WIN>
                  <WIN>
                    <OpenTaskWindow val="N"/>
                    <CloseTaskWindow val="Y"/>
                    <ForegroundWindow val="Y"/>
                    <FlipFld val="N"/>
                    <RefreshTaskWindow ReturnValue="N"/>
                  </WIN>
                  <BOX>
                    <Direction val="V"/>
                  </BOX>
                </Information>
                <TaskLogic>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="M"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <_TotalVariabls val="7"/>
                    <_TotalVirtuals val="7"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <DATAVIEW_SRC Type="M">
                          <Condition val="N"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </DATAVIEW_SRC>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="K">
                          <ASS/>
                          <Column val="1"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="L">
                          <ASS/>
                          <Column val="2"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="M">
                          <ASS/>
                          <Column val="3"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="N">
                          <ASS/>
                          <Column val="4"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="O">
                          <ASS/>
                          <Column val="5"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="P">
                          <ASS/>
                          <Column val="6"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="Q">
                          <ASS/>
                          <Column val="7"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="S"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***Begin Source Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Block SetParam RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="6"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="7"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Block SetParam RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="9"/>
                          <ReturnValue/>
                          <Condition Exp="8"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="10"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End SetParam XmlCnt RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Filter For Hole  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Filter For Hole  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="13"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***End Source Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=" **** Schema  Destination ****"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="14"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***Begin Update Destination Vars   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="K"/>
                          <WithValue val="15"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="L"/>
                          <WithValue val="16"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="M"/>
                          <WithValue val="17"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="N"/>
                          <WithValue val="18"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="O"/>
                          <WithValue val="19"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="P"/>
                          <WithValue val="20"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="Q"/>
                          <WithValue val="21"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***End Update Destination Vars   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Destination Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <FormIO>
                          <OperationType val="O"/>
                          <Page val="A"/>
                          <IODeviceInfo>
                            <IoDeviceParent val="3"/>
                            <IoDeviceIndex val="2"/>
                          </IODeviceInfo>
                          <FormEntryInfo>
                            <FormEntryIndex val="2"/>
                          </FormEntryInfo>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </FormIO>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Destination Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="P"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="T"/>
                    <Type val="P"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Temp SetParam TP   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="1"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="2"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="3"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Temp SetParam TP   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="T"/>
                    <Type val="S"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Temp SetParam TS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="4"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="5"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Temp SetParam TS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                </TaskLogic>
                <TaskForms>
                  <FormEntry _last_test_id="1">
                    <PropertyList model="FORM_GUI0">
                      <Width/>
                      <Height/>
                      <_Comment/>
                      <FormName valUnicode="Empty Program"/>
                    </PropertyList>
                  </FormEntry>
                </TaskForms>
                <TaskForms>
                  <FormEntry CLSS="8">
                    <PropertyList model="FORM_MERGE">
                      <FileName Exp="22"/>
                      <TagsTable>
                        <MERGE_PARM PIC_U="1" TXT_U="CheckDetail1" id="1" Column="K"/>
                        <MERGE_PARM PIC_U="1000" TXT_U="CHeader" id="2" Column="L" TEXP="23"/>
                        <MERGE_PARM PIC_U="1000" TXT_U="CRoot" id="3" Column="M" TEXP="24"/>
                        <MERGE_PARM PIC_U="1000" TXT_U="CLine" id="4" Column="N" TEXP="25"/>
                        <MERGE_PARM PIC_U="1000" TXT_U="CParentLine" id="5" Column="O" TEXP="26"/>
                        <MERGE_PARM PIC_U="1000" TXT_U="CTableName" id="6" Column="P" TEXP="27"/>
                        <MERGE_PARM PIC_U="1000" TXT_U="CVIN_NUMBER" id="7" Column="Q" TEXP="28"/>
                      </TagsTable>
                      <_Comment/>
                      <FormName valUnicode="Template Merge Destination_2"/>
                    </PropertyList>
                  </FormEntry>
                </TaskForms>
                <Expressions>
                  <Expression val="1">
                    <ExpSyntax val="SetParam('Temp_4_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="2">
                    <ExpSyntax val="SetParam('Temp_XMLCnt_4_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="3">
                    <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN',0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="4">
                    <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN',GetParam('Temp_4_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="5">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN',GetParam('Temp_XMLCnt_4_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="6">
                    <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN')"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="7">
                    <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN',0)"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="8">
                    <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN') =0"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="9">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN',XMLCnt(3,1,'/ZSERCAM01['&amp;Trim(Str(GetParam('S_1_7_39_3_ZSERCAM01'),''))&amp;']/IDOC['&amp;Trim(Str(GetParam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']/ZSCAMPAIGN['&amp;Trim(Str(GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']/ZSVIN'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="10">
                    <ExpSyntax val="SetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN',GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN')+1)"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="11">
                    <ExpSyntax val="GetParam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN')&gt;=GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN')"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="12">
                    <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="13">
                    <ExpSyntax val="GetParam('XMLCnt_S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN')&gt;0"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="14">
                    <ExpSyntax val="SetParam ('000000000001000000000007F.LineNo',GetParam ('000000000001000000000007F.LineNo') +1)"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="15">
                    <ExpSyntax val="'TRUE'LOG"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="16">
                    <ExpSyntax val="rTrim( 'i' )"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="17">
                    <ExpSyntax val="rTrim( 'c' )"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="18">
                    <ExpSyntax val="rTrim( Trim(Str( GetParam ('000000000001000000000007F.LineNo') ,'')) )"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="19">
                    <ExpSyntax val="rTrim( Trim(Str( GetParam ('000000000001000000000007F.ParentLineNo') ,'' )) )"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="20">
                    <ExpSyntax val="rTrim( 'CampaignConditions' )"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="21">
                    <ExpSyntax val="xmlget(3,1,'/ZSERCAM01['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC'),''))&amp;']'&amp;'/ZSCAMPAIGN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN'),''))&amp;']'&amp;'/ZSVIN['&amp;trim(str(getparam('S_1_7_39_3_ZSERCAM01/IDOC/ZSCAMPAIGN/ZSVIN'),''))&amp;']'&amp;'/VIN_NUMBER','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="22">
                    <ExpSyntax val="Translate(getFullPath('%Schema%ICRM003\ICRM003_Merge.txt'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="23">
                    <ExpSyntax val="Trim (Str (Len (RTrim (L)),'12'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="24">
                    <ExpSyntax val="Trim (Str (Len (RTrim (M)),'12'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="25">
                    <ExpSyntax val="Trim (Str (Len (RTrim (N)),'12'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="26">
                    <ExpSyntax val="Trim (Str (Len (RTrim (O)),'12'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="27">
                    <ExpSyntax val="Trim (Str (Len (RTrim (P)),'12'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="28">
                    <ExpSyntax val="Trim (Str (Len (RTrim (Q)),'12'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                </Expressions>
              </Task>
            </Task>
          </Task>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
