<?xml version="1.0" encoding="utf-8"?>
<Application>
  <ModelsRepository>
    <Models/>
  </ModelsRepository>
  <DataSourceRepository/>
  <Header>
    <Version val="12050"/>
    <APPLICATION val="Y"/>
    <WithIsn val="N"/>
    <Exe/>
    <_InternalTask/>
    <IsRoot/>
    <InIndex/>
    <WITH_MODELS/>
    <MAIN_PRG_VARS val="0"/>
    <MAIN_PRG_DSPS val="1"/>
    <Arguments END="2" START="2"/>
  </Header>
  <ProgramsRepository>
    <Programs>
      <Task>
        <Header Description="map_1_53_161">
          <Public val="map_1_53_161"/>
          <ExecutionRight/>
          <Resident val="N"/>
          <SQL val="N"/>
          <ReturnValue>
            <ReturnValueAttr/>
            <ParametersAttributes/>
          </ReturnValue>
          <SqlWhereExist val="N"/>
          <TaskType val="B"/>
          <External val="Y"/>
          <LastModified _date="737626" _time="38288" date="20//7//2020" time="10:38:08.4770937"/>
        </Header>
        <ReturnValueExpression/>
        <Resource>
          <Columns>
            <Column id="1" name="4_Destination_XMLIoPtrDll">
              <PropertyList model="FIELD">
                <Model attr_obj="FIELD_NUMERIC"/>
                <StoredAs/>
                <Size/>
                <_Dec/>
                <_Whole val="3"/>
                <_Negative/>
                <_FieldStyle val="1"/>
                <Picture valUnicode="3"/>
                <Definition val="2"/>
              </PropertyList>
            </Column>
          </Columns>
        </Resource>
        <Information>
          <Key>
            <Column/>
            <Mode val="N"/>
          </Key>
          <DB/>
          <Sort>
            <CLS val="A"/>
          </Sort>
          <ForceRecordDelete DEL="N"/>
          <EndTaskCondition val="Y"/>
          <EvaluateEndCondition val="A"/>
          <InitialMode val="M"/>
          <Locate Direction="A"/>
          <Range Direction="A"/>
          <VarRange/>
          <TaskProperties>
            <SelectionTable val="N"/>
            <ConfirmUpdate CNFU="N"/>
            <ConfirmCancel val="N"/>
            <ErrorStrategy val="R"/>
            <LockingStrategy val="M"/>
            <CacheStrategy val="T"/>
            <ForceRecordSuffix val="N"/>
            <TransactionMode val="P"/>
            <TransactionBegin val="N"/>
            <PreloadView val="N"/>
            <KeepCreatedContext val="N"/>
          </TaskProperties>
          <SIDE_WIN>
            <AllowOptions val="N"/>
            <AllowQuery val="Y"/>
            <AllowModify val="Y"/>
            <AllowCreate val="Y"/>
            <AllowDelete val="Y"/>
            <AllowLocate val="Y"/>
            <AllowRange val="Y"/>
            <AllowIndexChange val="Y"/>
            <AllowSorting val="Y"/>
            <AllowIOFiles val="Y"/>
            <RecordCycle val="Y"/>
            <AllowEvents val="Y"/>
            <AllowIndexOptimization val="Y"/>
            <AllowLocationInQuery val="Y"/>
            <AllowPrintingData val="N"/>
          </SIDE_WIN>
          <WIN>
            <OpenTaskWindow val="N"/>
            <CloseTaskWindow val="Y"/>
            <ForegroundWindow val="Y"/>
            <FlipFld val="N"/>
            <RefreshTaskWindow ReturnValue="N"/>
          </WIN>
          <BOX>
            <Direction val="V"/>
          </BOX>
        </Information>
        <TaskLogic>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="M"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <_TotalVariabls val="1"/>
            <_TotalVirtuals val="1"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <DATAVIEW_SRC Type="M">
                  <Condition val="N"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </DATAVIEW_SRC>
              </LogicLine>
              <LogicLine>
                <Select Name="A">
                  <ASS/>
                  <Column val="1"/>
                  <Type val="V"/>
                  <IsParameter val="N"/>
                  <_RecomputeIndex val="1"/>
                  <_FormIndex val="1"/>
                  <_ControlIndex val="1"/>
                  <_OleSubformIdx val="1"/>
                  <_TabbingOrderDspIndex val="1"/>
                  <DIFF_UPDATE val="T"/>
                  <Condition val="Y"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </Select>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="0"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
            <LogicLines>
              <LogicLine>
                <Evaluate>
                  <Expression val="1"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  BeginTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" Before CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="2"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="4"/>
                  <ReturnValue/>
                  <Condition Exp="3"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="5"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <CallTask>
                  <OperationType val="T"/>
                  <TaskID comp="-1" obj="1"/>
                  <Lock val="N"/>
                  <Arguments/>
                  <Wait val="Y"/>
                  <SyncData val="N"/>
                  <Condition Exp="6"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </CallTask>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="8"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="9"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="10"/>
                  <ReturnValue/>
                  <Condition Exp="7"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="11"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="12"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="13"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="14"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="7"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="15"/>
                  <ReturnValue/>
                  <Condition val="Y"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=" After CallTask"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="17"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="18"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="19"/>
                  <ReturnValue/>
                  <Condition Exp="16"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
              <LogicLine>
                <RaiseEvent>
                  <Event>
                    <EventType val="P"/>
                    <Exp val="20"/>
                    <PublicObject/>
                  </Event>
                  <Wait val="89"/>
                  <Arguments>
                    <Argument>
                      <id val="0"/>
                      <Expression val="21"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="22"/>
                      <Skip val="N"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Skip val="Y"/>
                    </Argument>
                    <Argument>
                      <id val="0"/>
                      <Expression val="23"/>
                      <Skip val="N"/>
                    </Argument>
                  </Arguments>
                  <Condition Exp="16"/>
                  <Modifier val="S"/>
                  <Direction val="C"/>
                </RaiseEvent>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="------------------------------"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val="********  EndTask-1********"/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Remark>
                  <Type val="2"/>
                  <Text val=""/>
                </Remark>
              </LogicLine>
              <LogicLine>
                <Evaluate>
                  <Expression val="25"/>
                  <ReturnValue/>
                  <Condition Exp="24"/>
                  <Modifier val="B"/>
                  <Direction val="C"/>
                </Evaluate>
              </LogicLine>
            </LogicLines>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="R"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="P"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
          <LogicUnit id="4" propagate="78">
            <Level val="T"/>
            <Type val="S"/>
            <_DspTemplate val="0"/>
            <_HeaderPosition val="3"/>
            <Scope val="S"/>
            <EngineDirective val="S"/>
            <ShowMessage val="Y"/>
            <Condition val="89"/>
            <Event>
              <EventType val="S"/>
              <ErrorTrigger/>
              <PublicObject obj="-1"/>
            </Event>
            <Expanded val="1"/>
          </LogicUnit>
        </TaskLogic>
        <TaskForms>
          <FormEntry _last_test_id="1">
            <PropertyList model="FORM_GUI0">
              <Width/>
              <Height/>
              <_Comment/>
              <FormName valUnicode="Empty Program"/>
            </PropertyList>
          </FormEntry>
        </TaskForms>
        <Expressions>
          <Expression val="1">
            <ExpSyntax val="SetParam('xmlErr',' ')"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="2">
            <ExpSyntax val="FileDelete(TranslateNR(getFullPath(RepStr ( GetParam ('000000000001000000000053F.TempFilePath') ,'.txt','.xml'))))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="3">
            <ExpSyntax val="getParam('Error')&lt;&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="4">
            <ExpSyntax val="setparam('MapperLastErrorCode',getparam('Error'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="5">
            <ExpSyntax val="setparam('Error',0)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="6">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (GetParam ('000000000001000000000053F.XMLpathfile')))))&gt;0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="7">
            <ExpSyntax val="FileSize(getFullPath(TranslateNR(Trim (GetParam ('000000000001000000000053F.XMLpathfile')))))=0"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="8">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="9">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source data does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="10">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="11">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="12">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="13">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="14">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="15">
            <ExpSyntax val="SetParam('xpi_SourceJsonIsNotWellFormed',NULL())"/>
            <ExpAttribute val="B"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="16">
            <ExpSyntax val="NOT(iBolt_FileExist (Trim(Flip(Del(Flip(TranslateNR(getFullPath(RepStr ( GetParam ('000000000001000000000053F.TempFilePath') ,'.txt','.xml')))),1,InStr(Flip(TranslateNR(getFullPath(RepStr ( GetParam ('000000000001000000000053F.TempFilePath') ,'.txt','.xml')))),trim(TranslateNR ('%sl%'))))))))"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="17">
            <ExpSyntax val="SetParam('Error',454)"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="18">
            <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Destination directory does not exist.'))"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="19">
            <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="20">
            <ExpSyntax val="'SaveInternalMSG'"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="21">
            <ExpSyntax val="15"/>
            <ExpAttribute val="N"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="22">
            <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
            <ExpAttribute val="A"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="23">
            <ExpSyntax val="'txt'"/>
            <ExpAttribute val="T"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="24">
            <ExpSyntax val="GetParam('xmlErr')&lt;&gt;''"/>
            <ExpAttribute val="L"/>
            <_ExeOnClient val="32"/>
          </Expression>
          <Expression val="25">
            <ExpSyntax val="SetParam('C.sys.LastErrorInfo',GetParam('xmlErr'))"/>
            <ExpAttribute val="*"/>
            <_ExeOnClient val="32"/>
          </Expression>
        </Expressions>
        <Task>
          <Header Description="NoSource_HyrarchiDestination">
            <Public/>
            <ExecutionRight/>
            <Resident val="N"/>
            <SQL val="N"/>
            <ReturnValue>
              <ReturnValueAttr/>
              <ParametersAttributes/>
            </ReturnValue>
            <SqlWhereExist val="N"/>
            <TaskType val="B"/>
            <External val="Y"/>
            <LastModified _date="737626" _time="38288" date="20//7//2020" time="10:38:08.4770937"/>
          </Header>
          <ReturnValueExpression/>
          <Resource>
            <IO>
              <Description val="xmlSource_1_53_161_5"/>
              <IOExpression val="1"/>
              <OpenPrintDialog val="N"/>
              <PaperSize val="68"/>
              <Format val="N"/>
              <Media val="D"/>
              <Access val="R"/>
              <Copies val="1"/>
              <Orientation val="P"/>
              <PrintPreview val="N"/>
              <Vis2LogTranslation val="N"/>
              <FlipLines val="N"/>
            </IO>
          </Resource>
          <Information>
            <Key>
              <Column/>
              <Mode val="N"/>
            </Key>
            <DB/>
            <Sort>
              <CLS val="A"/>
            </Sort>
            <ForceRecordDelete DEL="N"/>
            <EndTaskCondition val="Y"/>
            <EvaluateEndCondition val="A"/>
            <InitialMode val="M"/>
            <Locate Direction="A"/>
            <Range Direction="A"/>
            <VarRange/>
            <TaskProperties>
              <SelectionTable val="N"/>
              <ConfirmUpdate CNFU="N"/>
              <ConfirmCancel val="N"/>
              <ErrorStrategy val="R"/>
              <LockingStrategy val="M"/>
              <CacheStrategy val="T"/>
              <ForceRecordSuffix val="N"/>
              <TransactionMode val="P"/>
              <TransactionBegin val="N"/>
              <PreloadView val="N"/>
              <KeepCreatedContext val="N"/>
            </TaskProperties>
            <SIDE_WIN>
              <AllowOptions val="N"/>
              <AllowQuery val="Y"/>
              <AllowModify val="Y"/>
              <AllowCreate val="Y"/>
              <AllowDelete val="Y"/>
              <AllowLocate val="Y"/>
              <AllowRange val="Y"/>
              <AllowIndexChange val="Y"/>
              <AllowSorting val="Y"/>
              <AllowIOFiles val="Y"/>
              <RecordCycle val="Y"/>
              <AllowEvents val="Y"/>
              <AllowIndexOptimization val="Y"/>
              <AllowLocationInQuery val="Y"/>
              <AllowPrintingData val="N"/>
            </SIDE_WIN>
            <WIN>
              <OpenTaskWindow val="N"/>
              <CloseTaskWindow val="Y"/>
              <ForegroundWindow val="Y"/>
              <FlipFld val="N"/>
              <RefreshTaskWindow ReturnValue="N"/>
            </WIN>
            <BOX>
              <Direction val="V"/>
            </BOX>
          </Information>
          <TaskLogic>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="M"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <DATAVIEW_SRC Type="M">
                    <Condition val="N"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </DATAVIEW_SRC>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Update>
                    <Variable val="A"/>
                    <WithValue val="10"/>
                    <Incremental val="N"/>
                    <ForcedUpdate val="Y"/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Update>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="11"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="12"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <CallTask>
                    <OperationType val="T"/>
                    <TaskID comp="-1" obj="1"/>
                    <Lock val="N"/>
                    <Arguments/>
                    <Wait val="Y"/>
                    <SyncData val="N"/>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </CallTask>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="13"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="14"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="R"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="P"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
              <LogicLines>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   Begin ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                    <Condition Exp="2"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </BLOCK>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="3"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="4"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <Evaluate>
                    <Expression val="5"/>
                    <ReturnValue/>
                    <Condition val="Y"/>
                    <Modifier val="B"/>
                    <Direction val="C"/>
                  </Evaluate>
                </LogicLine>
                <LogicLine>
                  <RaiseEvent>
                    <Event>
                      <EventType val="P"/>
                      <Exp val="6"/>
                      <PublicObject/>
                    </Event>
                    <Wait val="89"/>
                    <Arguments>
                      <Argument>
                        <id val="0"/>
                        <Expression val="7"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="8"/>
                        <Skip val="N"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Skip val="Y"/>
                      </Argument>
                      <Argument>
                        <id val="0"/>
                        <Expression val="9"/>
                        <Skip val="N"/>
                      </Argument>
                    </Arguments>
                    <Condition val="Y"/>
                    <Modifier val="S"/>
                    <Direction val="C"/>
                  </RaiseEvent>
                </LogicLine>
                <LogicLine>
                  <END_BLK/>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val="***   End ErrorMsg   ***"/>
                  </Remark>
                </LogicLine>
                <LogicLine>
                  <Remark>
                    <Type val="2"/>
                    <Text val=""/>
                  </Remark>
                </LogicLine>
              </LogicLines>
            </LogicUnit>
            <LogicUnit id="4" propagate="78">
              <Level val="T"/>
              <Type val="S"/>
              <_DspTemplate val="0"/>
              <_HeaderPosition val="3"/>
              <Scope val="S"/>
              <EngineDirective val="S"/>
              <ShowMessage val="Y"/>
              <Condition val="89"/>
              <Event>
                <EventType val="S"/>
                <ErrorTrigger/>
                <PublicObject obj="-1"/>
              </Event>
              <Expanded val="1"/>
            </LogicUnit>
          </TaskLogic>
          <TaskForms>
            <FormEntry _last_test_id="1">
              <PropertyList model="FORM_GUI0">
                <Width/>
                <Height/>
                <_Comment/>
                <FormName valUnicode="Empty Program"/>
              </PropertyList>
            </FormEntry>
          </TaskForms>
          <Expressions>
            <Expression val="1">
              <ExpSyntax val="TranslateNR(getFullPath(GetParam ('000000000001000000000053F.XMLpathfile')))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="2">
              <ExpSyntax val="XMLCnt(0,1,'/IAFSR0041')=0"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="3">
              <ExpSyntax val="SetParam('Error',455)"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="4">
              <ExpSyntax val="SetParam ('C.sys.ErrorDescription',MlsTrans ('Source XML is not well-formed.'))"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="5">
              <ExpSyntax val="SetParam ('C.sys.LastErrorComponentType',11)"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="6">
              <ExpSyntax val="'SaveInternalMSG'"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="7">
              <ExpSyntax val="15"/>
              <ExpAttribute val="N"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="8">
              <ExpSyntax val="MlsTrans('Error  ')&amp;Trim(Str(GetParam('Error'),'12'))&amp;':'&amp;GetParam ('C.sys.ErrorDescription')"/>
              <ExpAttribute val="A"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="9">
              <ExpSyntax val="'txt'"/>
              <ExpAttribute val="T"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="10">
              <ExpSyntax val="UDF ('ibiowritter.openio',translatenr(getFullPath(RepStr ( GetParam ('000000000001000000000053F.TempFilePath') ,'.txt','.xml'))),'wb','16')"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="11">
              <ExpSyntax val="UDF ('ibiowritter.writeLnAsIs_w','&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; standalone=&quot;no&quot; ?&gt;',A)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="12">
              <ExpSyntax val="UDF ('ibiowritter.insertNS_w','xsi','http://www.w3.org/2001/XMLSchema-instance',A)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="13">
              <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','L','','','',A,0)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
            <Expression val="14">
              <ExpSyntax val="UDF ('ibiowritter.closeio',A)"/>
              <ExpAttribute val="*"/>
              <_ExeOnClient val="32"/>
            </Expression>
          </Expressions>
          <Task>
            <Header Description="IAFSR0041">
              <Public/>
              <ExecutionRight/>
              <Resident val="N"/>
              <SQL val="N"/>
              <ReturnValue>
                <ReturnValueAttr/>
                <ParametersAttributes/>
              </ReturnValue>
              <SqlWhereExist val="N"/>
              <TaskType val="B"/>
              <External val="Y"/>
              <LastModified _date="737626" _time="38288" date="20//7//2020" time="10:38:08.4927302"/>
            </Header>
            <ReturnValueExpression/>
            <Resource/>
            <Information>
              <Key>
                <Column/>
                <Mode val="N"/>
              </Key>
              <DB/>
              <Sort>
                <CLS val="A"/>
              </Sort>
              <ForceRecordDelete DEL="N"/>
              <EndTaskCondition val="Y" Exp="12"/>
              <EvaluateEndCondition val="A"/>
              <InitialMode val="M"/>
              <Locate Direction="A"/>
              <Range Direction="A"/>
              <VarRange/>
              <TaskProperties>
                <SelectionTable val="N"/>
                <ConfirmUpdate CNFU="N"/>
                <ConfirmCancel val="N"/>
                <ErrorStrategy val="R"/>
                <LockingStrategy val="M"/>
                <CacheStrategy val="T"/>
                <ForceRecordSuffix val="N"/>
                <TransactionMode val="P"/>
                <TransactionBegin val="N"/>
                <PreloadView val="N"/>
                <KeepCreatedContext val="N"/>
              </TaskProperties>
              <SIDE_WIN>
                <AllowOptions val="N"/>
                <AllowQuery val="Y"/>
                <AllowModify val="Y"/>
                <AllowCreate val="Y"/>
                <AllowDelete val="Y"/>
                <AllowLocate val="Y"/>
                <AllowRange val="Y"/>
                <AllowIndexChange val="Y"/>
                <AllowSorting val="Y"/>
                <AllowIOFiles val="Y"/>
                <RecordCycle val="Y"/>
                <AllowEvents val="Y"/>
                <AllowIndexOptimization val="Y"/>
                <AllowLocationInQuery val="Y"/>
                <AllowPrintingData val="N"/>
              </SIDE_WIN>
              <WIN>
                <OpenTaskWindow val="N"/>
                <CloseTaskWindow val="Y"/>
                <ForegroundWindow val="Y"/>
                <FlipFld val="N"/>
                <RefreshTaskWindow ReturnValue="N"/>
              </WIN>
              <BOX>
                <Direction val="V"/>
              </BOX>
            </Information>
            <TaskLogic>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="M"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <DATAVIEW_SRC Type="M">
                      <Condition val="N"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </DATAVIEW_SRC>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="6"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="7"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Block SetParam RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="9"/>
                      <ReturnValue/>
                      <Condition Exp="8"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="10"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End SetParam XmlCnt RS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For Hole  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                      <Condition Exp="13"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </BLOCK>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Source Builder   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=" **** Schema  Destination ****"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="14"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***Begin Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <CallTask>
                      <OperationType val="T"/>
                      <TaskID comp="-1" obj="1"/>
                      <Lock val="N"/>
                      <Arguments/>
                      <Wait val="Y"/>
                      <SyncData val="N"/>
                      <Condition val="Y"/>
                      <Modifier val="S"/>
                      <Direction val="C"/>
                    </CallTask>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="   ***End Update Destination Vars   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <END_BLK/>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="R"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="P"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="1"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="2"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="3"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TP   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
              <LogicUnit id="4" propagate="78">
                <Level val="T"/>
                <Type val="S"/>
                <_DspTemplate val="0"/>
                <_HeaderPosition val="3"/>
                <Scope val="S"/>
                <EngineDirective val="S"/>
                <ShowMessage val="Y"/>
                <Condition val="89"/>
                <Event>
                  <EventType val="S"/>
                  <ErrorTrigger/>
                  <PublicObject obj="-1"/>
                </Event>
                <Expanded val="1"/>
                <LogicLines>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   Begin Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="4"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Evaluate>
                      <Expression val="5"/>
                      <ReturnValue/>
                      <Condition val="Y"/>
                      <Modifier val="B"/>
                      <Direction val="C"/>
                    </Evaluate>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val="***   End Temp SetParam TS   ***"/>
                    </Remark>
                  </LogicLine>
                  <LogicLine>
                    <Remark>
                      <Type val="2"/>
                      <Text val=""/>
                    </Remark>
                  </LogicLine>
                </LogicLines>
              </LogicUnit>
            </TaskLogic>
            <TaskForms>
              <FormEntry _last_test_id="1">
                <PropertyList model="FORM_GUI0">
                  <Width/>
                  <Height/>
                  <_Comment/>
                  <FormName valUnicode="Empty Program"/>
                </PropertyList>
              </FormEntry>
            </TaskForms>
            <Expressions>
              <Expression val="1">
                <ExpSyntax val="SetParam('Temp_2_S_1_53_161_5_IAFSR0041_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_53_161_5_IAFSR0041'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="2">
                <ExpSyntax val="SetParam('Temp_XMLCnt_2_S_1_53_161_5_IAFSR0041_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_53_161_5_IAFSR0041'))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="3">
                <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041',0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="4">
                <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041',GetParam('Temp_2_S_1_53_161_5_IAFSR0041_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="5">
                <ExpSyntax val="SetParam('XMLCnt_S_1_53_161_5_IAFSR0041',GetParam('Temp_XMLCnt_2_S_1_53_161_5_IAFSR0041_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="6">
                <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041')&gt;=GetParam('XMLCnt_S_1_53_161_5_IAFSR0041')"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="7">
                <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041',0)"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="8">
                <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041') =0"/>
                <ExpAttribute val="A"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="9">
                <ExpSyntax val="SetParam('XMLCnt_S_1_53_161_5_IAFSR0041',XMLCnt(1,1,'/IAFSR0041'))"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="10">
                <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041',GetParam('S_1_53_161_5_IAFSR0041')+1)"/>
                <ExpAttribute val="N"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="11">
                <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041')&gt;=GetParam('XMLCnt_S_1_53_161_5_IAFSR0041')"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="12">
                <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="13">
                <ExpSyntax val="GetParam('XMLCnt_S_1_53_161_5_IAFSR0041')&gt;0"/>
                <ExpAttribute val="L"/>
                <_ExeOnClient val="32"/>
              </Expression>
              <Expression val="14">
                <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','C','IAFSR0041','IAFSR0041','',A,0)"/>
                <ExpAttribute val="*"/>
                <_ExeOnClient val="32"/>
              </Expression>
            </Expressions>
            <Task>
              <Header Description="IAFSR0041/IDOC">
                <Public/>
                <ExecutionRight/>
                <Resident val="N"/>
                <SQL val="N"/>
                <ReturnValue>
                  <ReturnValueAttr/>
                  <ParametersAttributes/>
                </ReturnValue>
                <SqlWhereExist val="N"/>
                <TaskType val="B"/>
                <External val="Y"/>
                <LastModified _date="737626" _time="38288" date="20//7//2020" time="10:38:08.4927302"/>
              </Header>
              <ReturnValueExpression/>
              <Resource/>
              <Information>
                <Key>
                  <Column/>
                  <Mode val="N"/>
                </Key>
                <DB/>
                <Sort>
                  <CLS val="A"/>
                </Sort>
                <ForceRecordDelete DEL="N"/>
                <EndTaskCondition val="Y" Exp="12"/>
                <EvaluateEndCondition val="A"/>
                <InitialMode val="M"/>
                <Locate Direction="A"/>
                <Range Direction="A"/>
                <VarRange/>
                <TaskProperties>
                  <SelectionTable val="N"/>
                  <ConfirmUpdate CNFU="N"/>
                  <ConfirmCancel val="N"/>
                  <ErrorStrategy val="R"/>
                  <LockingStrategy val="M"/>
                  <CacheStrategy val="T"/>
                  <ForceRecordSuffix val="N"/>
                  <TransactionMode val="P"/>
                  <TransactionBegin val="N"/>
                  <PreloadView val="N"/>
                  <KeepCreatedContext val="N"/>
                </TaskProperties>
                <SIDE_WIN>
                  <AllowOptions val="N"/>
                  <AllowQuery val="Y"/>
                  <AllowModify val="Y"/>
                  <AllowCreate val="Y"/>
                  <AllowDelete val="Y"/>
                  <AllowLocate val="Y"/>
                  <AllowRange val="Y"/>
                  <AllowIndexChange val="Y"/>
                  <AllowSorting val="Y"/>
                  <AllowIOFiles val="Y"/>
                  <RecordCycle val="Y"/>
                  <AllowEvents val="Y"/>
                  <AllowIndexOptimization val="Y"/>
                  <AllowLocationInQuery val="Y"/>
                  <AllowPrintingData val="N"/>
                </SIDE_WIN>
                <WIN>
                  <OpenTaskWindow val="N"/>
                  <CloseTaskWindow val="Y"/>
                  <ForegroundWindow val="Y"/>
                  <FlipFld val="N"/>
                  <RefreshTaskWindow ReturnValue="N"/>
                </WIN>
                <BOX>
                  <Direction val="V"/>
                </BOX>
              </Information>
              <TaskLogic>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="M"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <DATAVIEW_SRC Type="M">
                        <Condition val="N"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </DATAVIEW_SRC>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="6"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="7"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Block SetParam RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="9"/>
                        <ReturnValue/>
                        <Condition Exp="8"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="10"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End SetParam XmlCnt RS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For Hole  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                        <Condition Exp="13"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </BLOCK>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Source Builder   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=" **** Schema  Destination ****"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="14"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***Begin Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <CallTask>
                        <OperationType val="T"/>
                        <TaskID comp="-1" obj="1"/>
                        <Lock val="N"/>
                        <Arguments/>
                        <Wait val="Y"/>
                        <SyncData val="N"/>
                        <Condition val="Y"/>
                        <Modifier val="S"/>
                        <Direction val="C"/>
                      </CallTask>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="   ***End Update Destination Vars   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <END_BLK/>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="R"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="P"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="1"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="2"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="3"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TP   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
                <LogicUnit id="4" propagate="78">
                  <Level val="T"/>
                  <Type val="S"/>
                  <_DspTemplate val="0"/>
                  <_HeaderPosition val="3"/>
                  <Scope val="S"/>
                  <EngineDirective val="S"/>
                  <ShowMessage val="Y"/>
                  <Condition val="89"/>
                  <Event>
                    <EventType val="S"/>
                    <ErrorTrigger/>
                    <PublicObject obj="-1"/>
                  </Event>
                  <Expanded val="1"/>
                  <LogicLines>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   Begin Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="4"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Evaluate>
                        <Expression val="5"/>
                        <ReturnValue/>
                        <Condition val="Y"/>
                        <Modifier val="B"/>
                        <Direction val="C"/>
                      </Evaluate>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val="***   End Temp SetParam TS   ***"/>
                      </Remark>
                    </LogicLine>
                    <LogicLine>
                      <Remark>
                        <Type val="2"/>
                        <Text val=""/>
                      </Remark>
                    </LogicLine>
                  </LogicLines>
                </LogicUnit>
              </TaskLogic>
              <TaskForms>
                <FormEntry _last_test_id="1">
                  <PropertyList model="FORM_GUI0">
                    <Width/>
                    <Height/>
                    <_Comment/>
                    <FormName valUnicode="Empty Program"/>
                  </PropertyList>
                </FormEntry>
              </TaskForms>
              <Expressions>
                <Expression val="1">
                  <ExpSyntax val="SetParam('Temp_3_S_1_53_161_5_IAFSR0041/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_53_161_5_IAFSR0041/IDOC'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="2">
                  <ExpSyntax val="SetParam('Temp_XMLCnt_3_S_1_53_161_5_IAFSR0041/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC'))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="3">
                  <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC',0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="4">
                  <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC',GetParam('Temp_3_S_1_53_161_5_IAFSR0041/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="5">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC',GetParam('Temp_XMLCnt_3_S_1_53_161_5_IAFSR0041/IDOC_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="6">
                  <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041/IDOC')&gt;=GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC')"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="7">
                  <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC',0)"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="8">
                  <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041/IDOC') =0"/>
                  <ExpAttribute val="A"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="9">
                  <ExpSyntax val="SetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC',XMLCnt(2,1,'/IAFSR0041['&amp;Trim(Str(GetParam('S_1_53_161_5_IAFSR0041'),''))&amp;']/IDOC'))"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="10">
                  <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC',GetParam('S_1_53_161_5_IAFSR0041/IDOC')+1)"/>
                  <ExpAttribute val="N"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="11">
                  <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041/IDOC')&gt;=GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC')"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="12">
                  <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="13">
                  <ExpSyntax val="GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC')&gt;0"/>
                  <ExpAttribute val="L"/>
                  <_ExeOnClient val="32"/>
                </Expression>
                <Expression val="14">
                  <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','C','IDOC','IAFSR0041/IDOC','',A,0)"/>
                  <ExpAttribute val="*"/>
                  <_ExeOnClient val="32"/>
                </Expression>
              </Expressions>
              <Task>
                <Header Description="IAFSR0041/IDOC/IAFSR004">
                  <Public/>
                  <ExecutionRight/>
                  <Resident val="N"/>
                  <SQL val="N"/>
                  <ReturnValue>
                    <ReturnValueAttr/>
                    <ParametersAttributes/>
                  </ReturnValue>
                  <SqlWhereExist val="N"/>
                  <TaskType val="B"/>
                  <External val="Y"/>
                  <LastModified _date="737626" _time="38288" date="20//7//2020" time="10:38:08.4927302"/>
                </Header>
                <ReturnValueExpression/>
                <Resource>
                  <Columns>
                    <Column id="1" name="D_4_ParentLine">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="2" name="D_4_PersonalID">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="3" name="D_4_PassportNo">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="4" name="D_4_FirstName">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="5" name="D_4_LastName">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="6" name="D_4_CompanyRegID">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="7" name="D_4_CompanyName">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="8" name="D_4_RegistrationFlag">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="9" name="D_4_RegistrationDate">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="10" name="D_4_LineConnectivityFlag">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                    <Column id="11" name="D_4_LineRegistrationDate">
                      <PropertyList model="FIELD">
                        <Model attr_obj="FIELD_UNICODE"/>
                        <StoredAs val="32"/>
                        <Size val="2000"/>
                        <_FieldStyle val="1"/>
                        <Picture valUnicode="1000"/>
                        <Definition val="2"/>
                      </PropertyList>
                    </Column>
                  </Columns>
                </Resource>
                <Information>
                  <Key>
                    <Column/>
                    <Mode val="N"/>
                  </Key>
                  <DB/>
                  <Sort>
                    <CLS val="A"/>
                  </Sort>
                  <ForceRecordDelete DEL="N"/>
                  <EndTaskCondition val="Y" Exp="12"/>
                  <EvaluateEndCondition val="A"/>
                  <InitialMode val="M"/>
                  <Locate Direction="A"/>
                  <Range Direction="A"/>
                  <VarRange/>
                  <TaskProperties>
                    <SelectionTable val="N"/>
                    <ConfirmUpdate CNFU="N"/>
                    <ConfirmCancel val="N"/>
                    <ErrorStrategy val="R"/>
                    <LockingStrategy val="M"/>
                    <CacheStrategy val="T"/>
                    <ForceRecordSuffix val="N"/>
                    <TransactionMode val="P"/>
                    <TransactionBegin val="N"/>
                    <PreloadView val="N"/>
                    <KeepCreatedContext val="N"/>
                  </TaskProperties>
                  <SIDE_WIN>
                    <AllowOptions val="N"/>
                    <AllowQuery val="Y"/>
                    <AllowModify val="Y"/>
                    <AllowCreate val="Y"/>
                    <AllowDelete val="Y"/>
                    <AllowLocate val="Y"/>
                    <AllowRange val="Y"/>
                    <AllowIndexChange val="Y"/>
                    <AllowSorting val="Y"/>
                    <AllowIOFiles val="Y"/>
                    <RecordCycle val="Y"/>
                    <AllowEvents val="Y"/>
                    <AllowIndexOptimization val="Y"/>
                    <AllowLocationInQuery val="Y"/>
                    <AllowPrintingData val="N"/>
                  </SIDE_WIN>
                  <WIN>
                    <OpenTaskWindow val="N"/>
                    <CloseTaskWindow val="Y"/>
                    <ForegroundWindow val="Y"/>
                    <FlipFld val="N"/>
                    <RefreshTaskWindow ReturnValue="N"/>
                  </WIN>
                  <BOX>
                    <Direction val="V"/>
                  </BOX>
                </Information>
                <TaskLogic>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="M"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <_TotalVariabls val="11"/>
                    <_TotalVirtuals val="11"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <DATAVIEW_SRC Type="M">
                          <Condition val="N"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </DATAVIEW_SRC>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="B">
                          <ASS/>
                          <Column val="1"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="C">
                          <ASS/>
                          <Column val="2"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="D">
                          <ASS/>
                          <Column val="3"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="E">
                          <ASS/>
                          <Column val="4"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="F">
                          <ASS/>
                          <Column val="5"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="G">
                          <ASS/>
                          <Column val="6"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="H">
                          <ASS/>
                          <Column val="7"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="I">
                          <ASS/>
                          <Column val="8"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="J">
                          <ASS/>
                          <Column val="9"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="K">
                          <ASS/>
                          <Column val="10"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                      <LogicLine>
                        <Select Name="L">
                          <ASS/>
                          <Column val="11"/>
                          <Type val="V"/>
                          <IsParameter val="N"/>
                          <_RecomputeIndex val="1"/>
                          <_FormIndex val="1"/>
                          <_ControlIndex val="1"/>
                          <_OleSubformIdx val="1"/>
                          <_TabbingOrderDspIndex val="1"/>
                          <DIFF_UPDATE val="T"/>
                          <Condition val="Y"/>
                          <Modifier val="S"/>
                          <Direction val="C"/>
                        </Select>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="S"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***Begin Source Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Block SetParam RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="6"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="7"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Block SetParam RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin SetParam XmlCnt RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="9"/>
                          <ReturnValue/>
                          <Condition Exp="8"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="10"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End SetParam XmlCnt RS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Filter For Hole  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Filter For Hole  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Loop Filter For Connections Under Task  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Loop Filter For ConnectionsUnderTask  ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <BLOCK EndBlock="0" EndBlockSegment="0" Type="I">
                          <Condition Exp="13"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </BLOCK>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***End Source Builder   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=" **** Schema  Destination ****"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="14"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***Begin Update Destination Vars   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="B"/>
                          <WithValue val="15"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="16"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="C"/>
                          <WithValue val="17"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="18"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="D"/>
                          <WithValue val="19"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="20"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="E"/>
                          <WithValue val="21"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="22"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="F"/>
                          <WithValue val="23"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="24"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="G"/>
                          <WithValue val="25"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="26"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="H"/>
                          <WithValue val="27"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="28"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="I"/>
                          <WithValue val="29"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="30"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="J"/>
                          <WithValue val="31"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="32"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="K"/>
                          <WithValue val="33"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="34"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Update>
                          <Variable val="L"/>
                          <WithValue val="35"/>
                          <Incremental val="N"/>
                          <ForcedUpdate val="Y"/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Update>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="36"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="   ***End Update Destination Vars   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <END_BLK/>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="R"/>
                    <Type val="P"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="T"/>
                    <Type val="P"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Temp SetParam TP   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="1"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="2"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="3"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Temp SetParam TP   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                  <LogicUnit id="4" propagate="78">
                    <Level val="T"/>
                    <Type val="S"/>
                    <_DspTemplate val="0"/>
                    <_HeaderPosition val="3"/>
                    <Scope val="S"/>
                    <EngineDirective val="S"/>
                    <ShowMessage val="Y"/>
                    <Condition val="89"/>
                    <Event>
                      <EventType val="S"/>
                      <ErrorTrigger/>
                      <PublicObject obj="-1"/>
                    </Event>
                    <Expanded val="1"/>
                    <LogicLines>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   Begin Temp SetParam TS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="4"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Evaluate>
                          <Expression val="5"/>
                          <ReturnValue/>
                          <Condition val="Y"/>
                          <Modifier val="B"/>
                          <Direction val="C"/>
                        </Evaluate>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val="***   End Temp SetParam TS   ***"/>
                        </Remark>
                      </LogicLine>
                      <LogicLine>
                        <Remark>
                          <Type val="2"/>
                          <Text val=""/>
                        </Remark>
                      </LogicLine>
                    </LogicLines>
                  </LogicUnit>
                </TaskLogic>
                <TaskForms>
                  <FormEntry _last_test_id="1">
                    <PropertyList model="FORM_GUI0">
                      <Width/>
                      <Height/>
                      <_Comment/>
                      <FormName valUnicode="Empty Program"/>
                    </PropertyList>
                  </FormEntry>
                </TaskForms>
                <Expressions>
                  <Expression val="1">
                    <ExpSyntax val="SetParam('Temp_4_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="2">
                    <ExpSyntax val="SetParam('Temp_XMLCnt_4_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004_'&amp;Str(VarCurrN('P_FSID'),'12'),GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="3">
                    <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004',0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="4">
                    <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004',GetParam('Temp_4_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="5">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004',GetParam('Temp_XMLCnt_4_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004_'&amp;Str(VarCurrN('P_FSID'),'12')))"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="6">
                    <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004')&gt;=GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004')"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="7">
                    <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004',0)"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="8">
                    <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004') =0"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="9">
                    <ExpSyntax val="SetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004',XMLCnt(3,1,'/IAFSR0041['&amp;Trim(Str(GetParam('S_1_53_161_5_IAFSR0041'),''))&amp;']/IDOC['&amp;Trim(Str(GetParam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']/IAFSR004'))"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="10">
                    <ExpSyntax val="SetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004',GetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004')+1)"/>
                    <ExpAttribute val="N"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="11">
                    <ExpSyntax val="GetParam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004')&gt;=GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004')"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="12">
                    <ExpSyntax val="(ExpCalc('11'EXP) ) OR GetParam('Error')&lt;&gt;0"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="13">
                    <ExpSyntax val="GetParam('XMLCnt_S_1_53_161_5_IAFSR0041/IDOC/IAFSR004')&gt;0"/>
                    <ExpAttribute val="L"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="14">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','C','IAFSR004','IAFSR0041/IDOC/IAFSR004','',A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="15">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/ParentLine','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="16">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','ParentLine','IAFSR0041/IDOC/IAFSR004/ParentLine',rtrim(B),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="17">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/PersonalID','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="18">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','PersonalID','IAFSR0041/IDOC/IAFSR004/PersonalID',rtrim(C),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="19">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/PassportNo','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="20">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','PassportNo','IAFSR0041/IDOC/IAFSR004/PassportNo',rtrim(D),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="21">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/FirstName','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="22">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','FirstName','IAFSR0041/IDOC/IAFSR004/FirstName',rtrim(E),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="23">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/LastName','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="24">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','LastName','IAFSR0041/IDOC/IAFSR004/LastName',rtrim(F),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="25">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/CompanyRegID','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="26">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','CompanyRegID','IAFSR0041/IDOC/IAFSR004/CompanyRegID',rtrim(G),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="27">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/CompanyName','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="28">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','CompanyName','IAFSR0041/IDOC/IAFSR004/CompanyName',rtrim(H),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="29">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/RegistrationFlag','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="30">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','RegistrationFlag','IAFSR0041/IDOC/IAFSR004/RegistrationFlag',rtrim(I),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="31">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/RegistrationDate','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="32">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','RegistrationDate','IAFSR0041/IDOC/IAFSR004/RegistrationDate',rtrim(J),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="33">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/LineConnectivityFlag','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="34">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','LineConnectivityFlag','IAFSR0041/IDOC/IAFSR004/LineConnectivityFlag',rtrim(K),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="35">
                    <ExpSyntax val="xmlget(3,1,'/IAFSR0041['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041'),''))&amp;']'&amp;'/IDOC['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC'),''))&amp;']'&amp;'/IAFSR004['&amp;trim(str(getparam('S_1_53_161_5_IAFSR0041/IDOC/IAFSR004'),''))&amp;']'&amp;'/LineRegistrationDate','',SharedValGet('IB_NullifXMLSourceNonExistentTagValue'))"/>
                    <ExpAttribute val="A"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                  <Expression val="36">
                    <ExpSyntax val="UDFIB ('ibiowritter.ibioWritterGW','ibiowritter.writeSmart_w','S','LineRegistrationDate','IAFSR0041/IDOC/IAFSR004/LineRegistrationDate',rtrim(L),A,0)"/>
                    <ExpAttribute val="*"/>
                    <_ExeOnClient val="32"/>
                  </Expression>
                </Expressions>
              </Task>
            </Task>
          </Task>
        </Task>
      </Task>
      <SubTaskNumber/>
    </Programs>
  </ProgramsRepository>
</Application>
